/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HospitalCard: typeof import('./src/components/hospital/HospitalCard.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutElevator: typeof import('@nutui/nutui-taro')['Elevator']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutIcon: typeof import('@nutui/nutui-taro')['Icon']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutRate: typeof import('@nutui/nutui-taro')['Rate']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    SearchBar: typeof import('./src/components/base/SearchBar.vue')['default']
  }
}
